{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aura",
    "module": "aura-crypto",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.openquantumsafe",
          "module": "liboqs-java",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 145379,
          "sha512": "64d2b69f00bcfd7a9dc73e66003816b1a28c8ce3c2884de338b8b85eeeaed3b149fe6bbf53999a6a8948ca27ad1b9695fdca91d7b4e794824c5955394709a2f0",
          "sha256": "2aa6b9b8760b03edc89c383f90ff4bc96a100da3147f188d964a77b655aeec2e",
          "sha1": "eefa16051177fd49070c5c06fa2523b2548d477e",
          "md5": "139596f57a3201c586dc02f1857204b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.openquantumsafe",
          "module": "liboqs-java",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 145379,
          "sha512": "64d2b69f00bcfd7a9dc73e66003816b1a28c8ce3c2884de338b8b85eeeaed3b149fe6bbf53999a6a8948ca27ad1b9695fdca91d7b4e794824c5955394709a2f0",
          "sha256": "2aa6b9b8760b03edc89c383f90ff4bc96a100da3147f188d964a77b655aeec2e",
          "sha1": "eefa16051177fd49070c5c06fa2523b2548d477e",
          "md5": "139596f57a3201c586dc02f1857204b2"
        }
      ]
    }
  ]
}
