{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aura",
    "module": "aura-crypto",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 146586,
          "sha512": "75083db402d023baed29b272bc2653d5cef73eb2759d0babc3c6a5ce38d2e5510a69ade8edeb34152cbe2a2bc386f7d587fbac4ebf28461efd01f3eda5f219a1",
          "sha256": "220da0af95c0e7375a6ee781ef1023ca1c79fc933f240063532c17e72c1cad88",
          "sha1": "26b2552ddc2723cf665f59366636aa8a830a2751",
          "md5": "e2e5c78f35065c4780f0ae7f8a34ddc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 146586,
          "sha512": "75083db402d023baed29b272bc2653d5cef73eb2759d0babc3c6a5ce38d2e5510a69ade8edeb34152cbe2a2bc386f7d587fbac4ebf28461efd01f3eda5f219a1",
          "sha256": "220da0af95c0e7375a6ee781ef1023ca1c79fc933f240063532c17e72c1cad88",
          "sha1": "26b2552ddc2723cf665f59366636aa8a830a2751",
          "md5": "e2e5c78f35065c4780f0ae7f8a34ddc1"
        }
      ]
    }
  ]
}
