{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aura",
    "module": "aura-crypto",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 152418,
          "sha512": "3198a5545dae46ef286289011b5d3924465ccaa8112e8dd297adb280ce5e8bfa85066942a67755cac180ed0d443b1645c4acff9aa2f28c56a593823f563ac588",
          "sha256": "a18841cace677b0091968a41ae40c0035d2a9153de1ddf6506847c813934921e",
          "sha1": "854bdca529447f06214de95b5cdd24100b3862c4",
          "md5": "42a8c165dcb6705768bc55325d7d6b7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "aura-crypto-0.1.0.jar",
          "url": "aura-crypto-0.1.0.jar",
          "size": 152418,
          "sha512": "3198a5545dae46ef286289011b5d3924465ccaa8112e8dd297adb280ce5e8bfa85066942a67755cac180ed0d443b1645c4acff9aa2f28c56a593823f563ac588",
          "sha256": "a18841cace677b0091968a41ae40c0035d2a9153de1ddf6506847c813934921e",
          "sha1": "854bdca529447f06214de95b5cdd24100b3862c4",
          "md5": "42a8c165dcb6705768bc55325d7d6b7b"
        }
      ]
    }
  ]
}
